expressMoving/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^track_your_order/$', views.track_your_order, name='track_your_order'),
    url(r'^createNewOrder/', views.create_order, name='create_order'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^vehiclelist/$', views.VehicleList.as_view()),
    url(r'^vehicleTypelist/(?P<vehicle_id>[0-9]+)$', views.VehicleTypeList.as_view()),
    url(r'^config/(?P<variable>\w+)$', views.ConfigurationValue.as_view()),
    url(r'^trackYourOrder/(?P<tracking_id>\w+)$', views.TrackYourOrder.as_view()),
    url(r'^terms_and_conditions', views.terms_and_conditions, name='terms_and_conditions'),
    url(r'^privacy_policy', views.privacy_policy, name='privacy_policy'),
    url(r'^feedback', views.feedback, name='feedback'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Client(models.Model):
    mobile_no = models.CharField(max_length=25)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    createdAt = models.DateTimeField(editable=False)
    updateAt = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.createdAt = timezone.now()
        self.updateAt = timezone.now()
        return super(Client, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Vehicle(models.Model):
    type = models.CharField(max_length=50)
    enabled = models.BooleanField(default=True)
    createdAt = models.DateTimeField(editable=False)
    updateAt = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.createdAt = timezone.now()
        self.updateAt = timezone.now()
        return super(Vehicle, self).save(*args, **kwargs)

    def __str__(self):
        return self.type


class VehicleType(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    size = models.CharField(max_length=50)
    cost = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    enabled = models.BooleanField(default=True)
    vehicle_img = models.FileField(null=True)
    createdAt = models.DateTimeField(editable=False)
    updateAt = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.createdAt = timezone.now()
        self.updateAt = timezone.now()
        return super(VehicleType, self).save(*args, **kwargs)

    def __str__(self):
        return self.vehicle.type + " " + self.size


class Order(models.Model):
    order_type = (
        (0, 'Local'),
        (1, 'Long Distance'),
    )
    order_status = (
        (0, 'created'),
        (1, 'scheduled'),
        (2, 'delivered'),
        (3, 'canceled')
    )
    vehicle = models.ForeignKey(VehicleType, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    trackingId = models.CharField(db_index=True, max_length=50)
    totalCost = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    depositValue = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    pickFrom = models.CharField(max_length=1000)
    destinationTo = models.CharField(max_length=1000)
    orderType = models.IntegerField(choices=order_type)
    orderStatus = models.IntegerField(choices=order_status, default=0)
    noOfWorkers = models.IntegerField()
    noOFHours = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    createdAt = models.DateTimeField(editable=False)
    updateAt = models.DateTimeField()
    orderDate = models.DateField(null=False)
    fromTime = models.TimeField(null=False)
    toTime = models.TimeField(null=False)
    description = models.CharField(max_length=5000, null=True)
    url = models.CharField(max_length=80, null=True)
    enableTracking = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.createdAt = timezone.now()
        self.updateAt = timezone.now()
        return super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return self.trackingId


class Configuration(models.Model):
    variable = models.CharField(max_length=50)
    value = models.CharField(max_length=256)
    createdAt = models.DateTimeField(editable=False)
    updateAt = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.createdAt = timezone.now()
        self.updateAt = timezone.now()
        return super(Configuration, self).save(*args, **kwargs)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order
from django.contrib.admin import widgets

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    mobile_number = forms.RegexField(regex=r'\D*([2-9]\d{2})(\D*)([2-9]\d{2})(\D*)(\d{4})\D*', required=True)
    first_name = forms.CharField()
    last_name = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'mobile_number', 'last_name', 'email', 'password']

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class OrderForm(forms.ModelForm):
    # orderDate = forms.DateField(widget=forms.TextInput(attrs=
    # {
    #     'class': 'datepicker'
    # }))
    # fromTime = forms.TimeField(widget=forms.TimeInput)

    class Meta:
        model = Order
        fields = ['orderType', 'vehicle', 'noOfWorkers', 'noOFHours', 'orderDate', 'fromTime', 'toTime']

        def __init__(self, *args, **kwargs):
            super(OrderForm, self).__init__(*args, **kwargs)
            self.fields['orderDate'].widget = widgets.AdminDateWidget()
            self.fields['fromTime'].widget = widgets.AdminTimeWidget()
            self.fields['toTime'].widget = widgets.AdminTimeWidget()

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from .serializers import VehicleSerializer, VehicleTypeSerializer, ConfigurationTypeSerializer, OrderSerializer
from .forms import UserForm, OrderForm
from .models import Order, Client, Vehicle, VehicleType, Configuration
from rest_framework.views import APIView
from rest_framework.response import Response
from django.conf import settings


def index(request):
    return render(request, "main/index.html")


def about(request):
    # send_mail(
    #     'Subject here',
    #     'Here is the message.',
    #     'support@myexpressmove.com',
    #     ['engahmedkamal91@gmail.com'],
    #     fail_silently=False,
    # )
    return render(request, "main/about.html")


def terms_and_conditions(request):
    return render(request, "main/terms_and_conditions.html")


def privacy_policy(request):
    return render(request, "main/privacy_policy.html")


def contact(request):
    return render(request, "main/contact.html")


def feedback(request):
    # add message to response with success in case of sent
    context = {
        "feedback_sent": True,
    }
    return render(request, 'main/index.html', context)


def track_your_order(request):
    tracking_id = request.GET.get("tracking_id")
    order = get_object_or_404(Order, trackingId=tracking_id)
    return render(request, 'main/orderTracking.html', {'order': order})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'main/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('index')
            else:
                return render(request, 'main/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'main/login.html', {'error_message': 'Invalid login'})
    return render(request, 'main/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        mobileNumber = request.POST['mobile_number']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            client = Client(mobile_no=mobileNumber, user=user)
            client.save()
            login(request, user)
            return redirect('index')
    context = {
        "form": form,
    }
    return render(request, 'main/registration.html', context)


def create_order(request):
    if not request.user.is_authenticated:
        return redirect('login_user')
    else:
        form = OrderForm(request.POST or None)
        if form.is_valid():
            order = form.save(commit=False)
            # order.trackingId =
        context = {
            "form": form,
        }
        return render(request, "main/create_order.html", context)


class VehicleList(APIView):
    def get(self, request):
        vehicle = Vehicle.objects.filter(enabled=True)
        serializer = VehicleSerializer(vehicle, many=True)
        return Response(serializer.data)


class VehicleTypeList(APIView):
    def get(self, request, vehicle_id):
        vehicleType = VehicleType.objects.filter(enabled=True, vehicle=vehicle_id)
        serializer = VehicleTypeSerializer(vehicleType, many=True)
        return Response(serializer.data)


class ConfigurationValue(APIView):
    def get(self, request, variable):
        configuration = Configuration.objects.filter(variable=variable)
        serializer = ConfigurationTypeSerializer(configuration, many=True)
        return Response(serializer.data)


class TrackYourOrder(APIView):
    def get(self, request, tracking_id):
        order = Order.objects.filter(trackingId=tracking_id)
        if (not order):
            return Response({})
        serializer = OrderSerializer(order[0])
        return Response(serializer.data)

main/templates/main/404_main.html
{% extends 'main/base.html' %}
{% block title %}Error{% endblock %}
{% block headerStyle %}{% endblock %}
{% load staticfiles %}
{% block body %}
			<!-- Content-->
			<div class="md-content">
				<div class="consult-404">
					<div class="md-tb">
						<div class="md-tb__cell">
							<div class="container">
								<div class="row">
									<div class="col-lg-10 offset-0 offset-sm-0 offset-md-0 offset-lg-1 ">
										<div class="consult-404__content">
											<h1>404</h1>
											<h2>404 Opps! Page not found </h2>
											<p>It looks like nothing was found at this location. Click the link to return <a href="{% url 'index' %}">Home Page.</a> </p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- End / Content-->
{% endblock %}
{% block footer %}{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <title>{% block title %}Home{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="format-detection" content="telephone=no">
        <meta name="apple-mobile-web-app-capable" content="yes">

        {% load staticfiles %}
        <!-- Fonts-->
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/fonts/fontawesome/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/fonts/themify-icons/themify-icons.css' %}">
        <!-- Vendors-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'main/assets/vendors/bootstrap4/bootstrap-grid.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'main/assets/vendors/magnific-popup/magnific-popup.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/vendors/owl.carousel/owl.carousel.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/vendors/jquery.ui/jquery-ui.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'main/assets/vendors/jQuery.ui.timepicker/jquery-ui-timepicker-addon.min.css' %}">
        <!-- App & fonts-->
        <link rel="stylesheet" type="text/css"
              href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i&amp;amp;subset=latin-ext">
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main/assets/css/custom.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">

    </head>
</head>
<body>
<div class="page-wrap">

    <!-- header -->
    <header class="header {% block headerStyle %}header__style-02{% endblock %}">
        <div class="container">
            <div class="header__logo">
                <a href="/">
                    My Express Service
                </a>
                {% comment %}    <a href="{% url 'index' %}"><img src="{% static 'main/assets/img/logo.png' %}"
                                                                       alt=""/></a>{% endcomment %}
            </div>
            <div class="header__toogleGroup">
                <div class="search-form">
                    <div class="search-form__toggle">TRACK YOUR ORDER <i class="ti-search"></i></div>
                    <div class="search-form__form">
                        <div class="form-search">
                            <form role="search" method="get" action="{% url 'track_your_order' %}">
                                <input class="form-control" type="text" name="tracking_id"
                                       value="{{ request.GET.tracking_id }}"
                                       placeholder="Enter the Tracking Number and Hit enter to search or ESC to close"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- consult-nav -->
            <nav class="consult-nav">

                <!-- consult-menu -->
                <ul class="consult-menu">
                    <li class="{% block active_index %}{% endblock %}"><a href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="{% block active_about %}{% endblock %}"><a href="{% url 'about' %}">about</a>
                    </li>
                    <li class="{% block active_contact %}{% endblock %}"><a href="{% url 'contact' %}">contact</a>
                    </li>
                    {% if not user.is_authenticated %}
                        <li class="{% block active_register %}{% endblock %}"><a href="{% url 'register' %}">sign up</a>
                        </li>
                        <li class="{% block active_login %}{% endblock %}"><a href="{% url 'login_user' %}">login</a>
                        </li>
                    {% else %}
                        <li class="{% block active_create_order %}{% endblock %}"><a href="{% url 'create_order' %}">Create
                            Order</a>
                        </li>
                        <li class="{% block active_logout %}{% endblock %}"><a href="{% url 'logout_user' %}">log
                            out</a>
                        </li>
                    {% endif %}
                </ul><!-- consult-menu -->

                <div class="navbar-toggle"><span></span><span></span><span></span></div>
            </nav><!-- End / consult-nav -->

        </div>
    </header><!-- End / header -->

    <!-- Content-->
    {% block body %}
    {% endblock %}
    <!-- End / Content-->
    {% block footer %}
        <!-- footer -->
        <footer class="footer">
            <div class="footer__main">
                <div class="row " style="max-height: 250px;">
                    <div class="col-8 col-sm-7 col-md-9 col-lg-3 ">
                        <div class="footer__item"><a class="consult_logo" href="#"><img
                                src="{% static 'main/assets/img/logo.png' %}"
                                alt=""/></a>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2 offset-0 offset-sm-0 offset-md-0 offset-lg-0 offset-xl-1 ">
                        <div class="footer__item">

                            <!-- widget-text__widget -->
                            <section class="widget-text__widget widget">
                                <div class="widget-text__content">
                                    <ul>
                                        <li><a href="{% url 'terms_and_conditions' %}">Terms and conditions </a></li>
                                        <li><a href="{% url 'privacy_policy' %}">Privacy Policy </a></li>
                                        {% comment %}<li><a href="#">Sitemap </a></li>{% endcomment %}
                                        {% comment %}<li><a href="#">Help</a></li>{% endcomment %}
                                    </ul>
                                </div>
                            </section><!-- End / widget-text__widget -->

                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-1 col-xl-1 ">
                        <div class="footer__item">

                            <!-- widget-text__widget -->
                            <section class="widget-text__widget widget">
                                <div class="widget-text__content">
                                    <ul>
                                        {% comment %}<li><a href="#">How It Work </a></li>
                                        <li><a href="#">Carrier </a></li>
                                        <li><a href="#">Pricing </a></li>{% endcomment %}
                                        <li><a href="{% url 'contact' %}">Support</a></li>
                                    </ul>
                                </div>
                            </section><!-- End / widget-text__widget -->

                        </div>
                    </div>
                    <div class="col-md-4 col-lg-3 col-xl-3 ">
                        <div class="footer__item">

                            <div class="footer__item" style="margin-bottom: 0px;">
                                Find Us
                            </div>

                            <div class="footer__item">
                                <a class="social-01__item" href="https://www.facebook.com/myexpressservice/"
                                   target="_blank"><i
                                        class="fa fa-facebook" style="font-size: 3em;"></i>
                                </a>
                                <a class="social-01__item" href="https://www.instagram.com/myexpressservice/"
                                   target="_blank"><i
                                        class="fa fa-instagram" style="font-size: 3em;"></i>
                                </a>
                                <a class="social-01__item"
                                   href="https://www.youtube.com/channel/UCPCIQIjS9T372oO_oY8lINA" target="_blank"><i
                                        class="fa fa-youtube" style="font-size: 3em;"></i>
                                </a>
                            </div>

                            {% comment %}<!-- form-sub -->
                            <div class="form-sub">
                                <h4 class="form-sub__title">Our Newsletter</h4>
                                <form class="form-sub__form">
                                    <div class="form-item">
                                        <input class="form-control" type="email"
                                               placeholder="Enter Your Email Address..."/>
                                    </div>
                                    <div class="form-submit">
                                        <button class="form-button" type="submit"><i class="fa fa-paper-plane"
                                                                                     aria-hidden="true"></i></button>
                                    </div>
                                </form>
                            </div><!-- End / form-sub -->{% endcomment %}

                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-2 col-xl-2  consult_backToTop">
                        <div class="footer__item"><a href="#" id="back-to-top"> <i class="fa fa-angle-up"
                                                                                   aria-hidden="true"> </i><span>Back To Top</span></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer__copyright">2018 &copy; Copyright My Express Service LLC. All rights Reserved.</div>
        </footer><!-- End / footer -->
    {% endblock %}
</div>
<!-- Vendors-->
<script type="text/javascript" src="{% static 'main/assets/vendors/jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/imagesloaded/imagesloaded.pkgd.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/isotope-layout/isotope.pkgd.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/jquery.countdown/jquery.countdown.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/jquery.countTo/jquery.countTo.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/jquery.countUp/jquery.countup.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/jquery.matchHeight/jquery.matchHeight.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/jquery.mb.ytplayer/jquery.mb.YTPlayer.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/masonry-layout/masonry.pkgd.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/owl.carousel/owl.carousel.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/jquery.waypoints/jquery.waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/menu/menu.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/smoothscroll/SmoothScroll.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/assets/vendors/jquery.ui/jquery-ui.min.js' %}"></script>
<script type="text/javascript"
        src="{% static 'main/assets/vendors/jQuery.ui.timepicker/jquery-ui-timepicker-addon.min.js' %}"></script>
<!-- App-->
<script type="text/javascript" src="{% static 'main/assets/js/main.js' %}"></script>


<script type="text/javascript">

    $(document).ready(function () {

        $(".datepicker").datepicker({
            showButtonPanel: true,
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy'
        });

        $(".timepicker").timepicker();

        $('.magnific-popup').magnificPopup({type: 'image'});
    });

</script>


<!-- footer javascript-->
{% block footerJavascript %}
{% endblock %}
<!-- End / footer javascript-->

</body>
</html>

main/templates/main/create_order.html
{% extends 'main/base.html' %}
{% block title %}Schedule New Order{% endblock %}
{% block headerStyle %}{% endblock %}
{% block active_create_order %}current-menu-item{% endblock %}
{% block body %}
    <div class="md-content">
        <section class="md-section">
            <div class="container">
                <form class="form-horizontal" action='{% url 'register' %}' method="POST">
                    {% csrf_token %}
                    <fieldset>
                        <div id="legend">
                            <legend class="">Schedule New Order</legend>
                        </div>
{#                        <div class="control-group">#}
{#                            <label class="control-label" for="orderType">Order type:</label>#}
{#                            <div class="controls">#}
{#                                 <label class="radio-inline">#}
{#                                <input type="radio" name="orderType" value="Local" checked>Local Within New Jersey#}
{#                            </label>#}
{#                            <label class="radio-inline">#}
{#                                <input type="radio" name="orderType" disabled>Long Distance Not available online please contact us#}
{#                            </label>#}
{#                            </div>#}
{#                        </div>#}
                        {% include 'main/form_template.html' %}

                        <div class="control-group">
                            <!-- Button -->
                            <div class="controls">
                                <button class="btn btn-success">CheckOut</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </section>
    </div>
{% endblock %}

main/templates/main/form_template.html
{{ form.non_field_errors }}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block title %}Login{% endblock %}
{% block headerStyle %}{% endblock %}
{% block active_login %}current-menu-item{% endblock %}
{% block body %}
    <div class="md-content">
        <!-- Section -->
        <section class="md-section">
            <div class="container">
                <form class="form-horizontal" action='{% url 'login_user' %}' method="POST">
                    {% csrf_token %}
                    <fieldset>
                        <div id="legend">
                            <legend class="">Login</legend>
                            {% if error_message %}
                                <p><strong>{{ error_message }}</strong></p>
                            {% endif %}
                        </div>
                        <div class="control-group">
                            <!-- Username -->
                            <div class="controls">
                                <input type="text" id="username" name="username" placeholder="username"
                                       class="input-large">
                            </div>
                        </div>
                        <div class="control-group">
                            <!-- Password -->
                            <div class="controls">
                                <input type="password" id="password" name="password" placeholder="password"
                                       class="input-large">
                            </div>
                        </div>

                        <div class="control-group">
                            <!-- Button -->
                            <div class="controls">
                                <button class="btn btn-primary">Login</button>
                            </div>
                            <div class="panel-footer">
                                Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.
                            </div>

                        </div>
                    </fieldset>
                </form>
            </div>
        </section>
    </div>
{% endblock %}

main/templates/main/orderTracking.html
{% extends 'main/base.html' %}
{% block title %}Order Details{% endblock %}
{% block headerStyle %}{% endblock %}
{% block body %}
    <div class="md-content">

        <!-- Section -->
        <section class="md-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 col-xl-8 offset-0 offset-sm-0 offset-md-0 offset-lg-1 offset-xl-2 ">

                        <!-- title-01 -->
                        <div class="title-01 title-01__style-04">
                            <h6 class="title-01__subTitle">Order tracking Id:-{{ order.trackingId }}</h6>
                            <h2 class="title-01__title">Status : {{ order.get_orderStatus_display }}</h2>
                            <div>
                                    For more information contact : 888-888-888
                            </div>
                        </div><!-- End / title-01 -->

                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}